### PR TITLE
prefer APP_ENV to RACK_ENV

### PR DESCRIPTION
**Pull request by notEthan**
this change follows https://github.com/sinatra/sinatra/pull/984

### CODE REVIEW

**Comment by notEthan** [comment]
I think that, for consistency, it would be better if this could look at the sinatra `app.settings.environment` 

this relates to issue https://github.com/janko-m/sinatra-activerecord/issues/77 which is not looking at the environment configured there.

if the maintainer(s) agree I could have a crack at implementing it that way.

**Comment by scarfacedeb** [comment]
Well, it's been almost 2 years. But is there a change that it'll be merged as is?

**Comment by abrahamcuenca** [comment]
Is this MR still relevant?

**Comment by cupnoodle** [comment]
Looks good to me

**Pull request merged**
