### PR TITLE
Update with activerecord 7

### PR DESCRIPTION
**Pull request by colinbruce**
Duplicate the rake file from activerecord_6 and update the Contributing guide

### CODE REVIEW

**Comment by jeroennijhof** [comment]
@colinbruce you forgot to add the activerecord_7 file.

**Comment by jeroennijhof** [comment]
:+1:

**Comment by colinbruce** [comment]
Thanks for pointing it out 👍 
That was a bit of a 🤦 moment!

**Comment by jeroennijhof** [comment]
@cupnoodle do you have time to look at this?

**Comment by cupnoodle** [comment]
> @cupnoodle do you have time to look at this?

Sure! Thanks for the PR, I will look into it soon

**Comment by colinbruce** [comment]
Sorry @cupnoodle I overlooked the workflow for the addition of ActiveRecord 7 to the matrix

**Comment by colinbruce** [comment]
This is going poorly 😕 
I'm going to close this for now and resolve the issues on my fork and then re-open

**Comment by cupnoodle** [comment]
> This is going poorly 😕
> I'm going to close this for now and resolve the issues on my fork and then re-open

No worries, I appreciate your effort, thanks!  🙏

**Pull request closed without merging**
