### PR TITLE
chore: add support for activerecord 8

### PR DESCRIPTION
**Pull request by scbjans**
Added support for activerecord8. 
Cleaned up CI a bit by moving the excludes from the testmatrix into the `Appraisals`.

Should fix https://github.com/sinatra-activerecord/sinatra-activerecord/issues/134

### CODE REVIEW

**Comment by scbjans** [comment]
@cupnoodle could you please review this PR?

**Comment by cupnoodle** [comment]
Seems like there was some Ruby version issue on the CI, can you try revert removing the "exclude" part on the CI matrix?

**Comment by scbjans** [comment]
> Seems like there was some Ruby version issue on the CI, can you try revert removing the "exclude" part on the CI matrix?

Thank you, I've re-added the exclusions to CI in c5c7a3bc9b14f9ffa5449c10a4f501a8db9ff7f0

**Comment by scbjans** [comment]
I'm not sure why CI Jobs `Test (3.1, 6.0)` and `Test (3.1, 6.1)` try to install activerecord 8 instead of the specified `6.0` and `6.1`. Do you have any idea?

**Comment by cupnoodle** [comment]
My guess is that there might be some issue with bundler and the sqlite3 gem (version 2.0 and above),  I have managed to fix the issues by fixing the bundler version to 2.4.22, and sqlite3 gem version to ~1.4.

I have made a new PR for this fix here : #136  , would you mind taking a look and see if it looks ok? I will merge it if there's no issue

**Comment by cupnoodle** [comment]
Merged #136 to master

**Pull request closed without merging**
